//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B20.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name ProcitajSveValuteResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajSveValute", ReplyAction="*")]
        B20.ServiceReference1.ProcitajSveValuteResponse ProcitajSveValute(B20.ServiceReference1.ProcitajSveValuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajSveValute", ReplyAction="*")]
        System.Threading.Tasks.Task<B20.ServiceReference1.ProcitajSveValuteResponse> ProcitajSveValuteAsync(B20.ServiceReference1.ProcitajSveValuteRequest request);
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajKursNaDan", ReplyAction="*")]
        B20.ServiceReference1.ProcitajKursNaDanResponse ProcitajKursNaDan(B20.ServiceReference1.ProcitajKursNaDanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcitajKursNaDan", ReplyAction="*")]
        System.Threading.Tasks.Task<B20.ServiceReference1.ProcitajKursNaDanResponse> ProcitajKursNaDanAsync(B20.ServiceReference1.ProcitajKursNaDanRequest request);
        
        // CODEGEN: Generating message contract since element name valuta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpisiKursNaDan", ReplyAction="*")]
        B20.ServiceReference1.UpisiKursNaDanResponse UpisiKursNaDan(B20.ServiceReference1.UpisiKursNaDanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpisiKursNaDan", ReplyAction="*")]
        System.Threading.Tasks.Task<B20.ServiceReference1.UpisiKursNaDanResponse> UpisiKursNaDanAsync(B20.ServiceReference1.UpisiKursNaDanRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajSveValuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajSveValute", Namespace="http://tempuri.org/", Order=0)]
        public B20.ServiceReference1.ProcitajSveValuteRequestBody Body;
        
        public ProcitajSveValuteRequest() {
        }
        
        public ProcitajSveValuteRequest(B20.ServiceReference1.ProcitajSveValuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ProcitajSveValuteRequestBody {
        
        public ProcitajSveValuteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajSveValuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajSveValuteResponse", Namespace="http://tempuri.org/", Order=0)]
        public B20.ServiceReference1.ProcitajSveValuteResponseBody Body;
        
        public ProcitajSveValuteResponse() {
        }
        
        public ProcitajSveValuteResponse(B20.ServiceReference1.ProcitajSveValuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajSveValuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B20.ServiceReference1.ArrayOfString ProcitajSveValuteResult;
        
        public ProcitajSveValuteResponseBody() {
        }
        
        public ProcitajSveValuteResponseBody(B20.ServiceReference1.ArrayOfString ProcitajSveValuteResult) {
            this.ProcitajSveValuteResult = ProcitajSveValuteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajKursNaDanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajKursNaDan", Namespace="http://tempuri.org/", Order=0)]
        public B20.ServiceReference1.ProcitajKursNaDanRequestBody Body;
        
        public ProcitajKursNaDanRequest() {
        }
        
        public ProcitajKursNaDanRequest(B20.ServiceReference1.ProcitajKursNaDanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajKursNaDanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Datum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        public ProcitajKursNaDanRequestBody() {
        }
        
        public ProcitajKursNaDanRequestBody(System.DateTime Datum, string valuta) {
            this.Datum = Datum;
            this.valuta = valuta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcitajKursNaDanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcitajKursNaDanResponse", Namespace="http://tempuri.org/", Order=0)]
        public B20.ServiceReference1.ProcitajKursNaDanResponseBody Body;
        
        public ProcitajKursNaDanResponse() {
        }
        
        public ProcitajKursNaDanResponse(B20.ServiceReference1.ProcitajKursNaDanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcitajKursNaDanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double ProcitajKursNaDanResult;
        
        public ProcitajKursNaDanResponseBody() {
        }
        
        public ProcitajKursNaDanResponseBody(double ProcitajKursNaDanResult) {
            this.ProcitajKursNaDanResult = ProcitajKursNaDanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpisiKursNaDanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpisiKursNaDan", Namespace="http://tempuri.org/", Order=0)]
        public B20.ServiceReference1.UpisiKursNaDanRequestBody Body;
        
        public UpisiKursNaDanRequest() {
        }
        
        public UpisiKursNaDanRequest(B20.ServiceReference1.UpisiKursNaDanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpisiKursNaDanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime Datum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string valuta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double Kurs;
        
        public UpisiKursNaDanRequestBody() {
        }
        
        public UpisiKursNaDanRequestBody(System.DateTime Datum, string valuta, double Kurs) {
            this.Datum = Datum;
            this.valuta = valuta;
            this.Kurs = Kurs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpisiKursNaDanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpisiKursNaDanResponse", Namespace="http://tempuri.org/", Order=0)]
        public B20.ServiceReference1.UpisiKursNaDanResponseBody Body;
        
        public UpisiKursNaDanResponse() {
        }
        
        public UpisiKursNaDanResponse(B20.ServiceReference1.UpisiKursNaDanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpisiKursNaDanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpisiKursNaDanResult;
        
        public UpisiKursNaDanResponseBody() {
        }
        
        public UpisiKursNaDanResponseBody(bool UpisiKursNaDanResult) {
            this.UpisiKursNaDanResult = UpisiKursNaDanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : B20.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<B20.ServiceReference1.WebService1Soap>, B20.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B20.ServiceReference1.ProcitajSveValuteResponse B20.ServiceReference1.WebService1Soap.ProcitajSveValute(B20.ServiceReference1.ProcitajSveValuteRequest request) {
            return base.Channel.ProcitajSveValute(request);
        }
        
        public B20.ServiceReference1.ArrayOfString ProcitajSveValute() {
            B20.ServiceReference1.ProcitajSveValuteRequest inValue = new B20.ServiceReference1.ProcitajSveValuteRequest();
            inValue.Body = new B20.ServiceReference1.ProcitajSveValuteRequestBody();
            B20.ServiceReference1.ProcitajSveValuteResponse retVal = ((B20.ServiceReference1.WebService1Soap)(this)).ProcitajSveValute(inValue);
            return retVal.Body.ProcitajSveValuteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B20.ServiceReference1.ProcitajSveValuteResponse> B20.ServiceReference1.WebService1Soap.ProcitajSveValuteAsync(B20.ServiceReference1.ProcitajSveValuteRequest request) {
            return base.Channel.ProcitajSveValuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<B20.ServiceReference1.ProcitajSveValuteResponse> ProcitajSveValuteAsync() {
            B20.ServiceReference1.ProcitajSveValuteRequest inValue = new B20.ServiceReference1.ProcitajSveValuteRequest();
            inValue.Body = new B20.ServiceReference1.ProcitajSveValuteRequestBody();
            return ((B20.ServiceReference1.WebService1Soap)(this)).ProcitajSveValuteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B20.ServiceReference1.ProcitajKursNaDanResponse B20.ServiceReference1.WebService1Soap.ProcitajKursNaDan(B20.ServiceReference1.ProcitajKursNaDanRequest request) {
            return base.Channel.ProcitajKursNaDan(request);
        }
        
        public double ProcitajKursNaDan(System.DateTime Datum, string valuta) {
            B20.ServiceReference1.ProcitajKursNaDanRequest inValue = new B20.ServiceReference1.ProcitajKursNaDanRequest();
            inValue.Body = new B20.ServiceReference1.ProcitajKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            B20.ServiceReference1.ProcitajKursNaDanResponse retVal = ((B20.ServiceReference1.WebService1Soap)(this)).ProcitajKursNaDan(inValue);
            return retVal.Body.ProcitajKursNaDanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B20.ServiceReference1.ProcitajKursNaDanResponse> B20.ServiceReference1.WebService1Soap.ProcitajKursNaDanAsync(B20.ServiceReference1.ProcitajKursNaDanRequest request) {
            return base.Channel.ProcitajKursNaDanAsync(request);
        }
        
        public System.Threading.Tasks.Task<B20.ServiceReference1.ProcitajKursNaDanResponse> ProcitajKursNaDanAsync(System.DateTime Datum, string valuta) {
            B20.ServiceReference1.ProcitajKursNaDanRequest inValue = new B20.ServiceReference1.ProcitajKursNaDanRequest();
            inValue.Body = new B20.ServiceReference1.ProcitajKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            return ((B20.ServiceReference1.WebService1Soap)(this)).ProcitajKursNaDanAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B20.ServiceReference1.UpisiKursNaDanResponse B20.ServiceReference1.WebService1Soap.UpisiKursNaDan(B20.ServiceReference1.UpisiKursNaDanRequest request) {
            return base.Channel.UpisiKursNaDan(request);
        }
        
        public bool UpisiKursNaDan(System.DateTime Datum, string valuta, double Kurs) {
            B20.ServiceReference1.UpisiKursNaDanRequest inValue = new B20.ServiceReference1.UpisiKursNaDanRequest();
            inValue.Body = new B20.ServiceReference1.UpisiKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            inValue.Body.Kurs = Kurs;
            B20.ServiceReference1.UpisiKursNaDanResponse retVal = ((B20.ServiceReference1.WebService1Soap)(this)).UpisiKursNaDan(inValue);
            return retVal.Body.UpisiKursNaDanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<B20.ServiceReference1.UpisiKursNaDanResponse> B20.ServiceReference1.WebService1Soap.UpisiKursNaDanAsync(B20.ServiceReference1.UpisiKursNaDanRequest request) {
            return base.Channel.UpisiKursNaDanAsync(request);
        }
        
        public System.Threading.Tasks.Task<B20.ServiceReference1.UpisiKursNaDanResponse> UpisiKursNaDanAsync(System.DateTime Datum, string valuta, double Kurs) {
            B20.ServiceReference1.UpisiKursNaDanRequest inValue = new B20.ServiceReference1.UpisiKursNaDanRequest();
            inValue.Body = new B20.ServiceReference1.UpisiKursNaDanRequestBody();
            inValue.Body.Datum = Datum;
            inValue.Body.valuta = valuta;
            inValue.Body.Kurs = Kurs;
            return ((B20.ServiceReference1.WebService1Soap)(this)).UpisiKursNaDanAsync(inValue);
        }
    }
}
